""":mod:`cliche.cli` --- Command-line interfaces
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"""
import code
import functools
import logging.config
import os
import pathlib
import sys

from alembic.util import CommandError
from click import Path, argument, echo, group, option
from flask import _request_ctx_stack
from sassutils.wsgi import SassMiddleware
from werkzeug.utils import import_string

from .celery import app as celery_app
from .config import read_config
from .name import Name
from .orm import Base, downgrade_database, upgrade_database
from .sqltypes import HashableLocale
from .web.app import (app as flask_app,
                      setup_sentry as flask_setup_sentry)
from .web.db import get_database_engine, session
from .work import Trope, Work
from .services.align import alignment


__all__ = ('initialize_app', 'config', 'main')

ALEMBIC_LOGGING = {
    'version': 1,
    'handlers': {
        'console': {
            'level': 'NOTSET',
            'class': 'logging.StreamHandler',
            'formatter': 'generic'
        }
    },
    'formatters': {
        'generic': {
            'format': '%(levelname)-5.5s [%(name)s] %(message)s',
            'datefmt': '%H:%M:%S'
        }
    },
    'root': {
        'level': 'WARN',
        'handlers': ['console']
    },
    'loggers': {
        'alembic': {
            'level': 'INFO',
            'handlers': []
        },
        'sqlalchemy.engine': {
            'level': 'WARN',
            'handlers': []
        }
    }
}


def config(func):
    """Provide :option:`--config` or :option:`-c` option and
    run :func:`initialize_app()` automatically.

    :param func: a command function to decorate
    :type func: :class:`collections.abc.Callable`
    :returns: decorated ``func``

    """
    @functools.wraps(func)
    def internal(*args, **kwargs):
        initialize_app(kwargs.pop('config'))
        func(*args, **kwargs)

    deco = option('--config', '-c', type=Path(exists=True),
                  help='Configuration file (YAML or Python)')
    return deco(internal)


def initialize_app(config=None):
    """Initialize celery/flask app.

    :param config: a config file path. accept :file:`.py`, :file:`.yml` file.
                   default value is :const:`None`

    """
    if config is None:
        try:
            config = os.environ['CLICHE_CONFIG']
        except KeyError:
            print('The -c/--config option or CLICHE_CONFIG environment '
                  'variable is required', file=sys.stderr)
            raise SystemExit(1)
    if not os.path.isfile(config):
        print('The configuration file', config, 'cannot be read.')
        raise SystemExit(1)
    config = read_config(filename=pathlib.Path(config))
    flask_app.config.update(config)
    celery_app.conf.update(config)


@group()
def cli():
    """cliche for integrated command for cliche.io service."""


@cli.command()
@argument('revision', default='head')
@config
def upgrade(revision):
    """Create the database tables, or upgrade it to the latest revision."""

    logging_config = dict(ALEMBIC_LOGGING)
    logging.config.dictConfig(logging_config)
    with flask_app.app_context():
        engine = get_database_engine()
        try:
            upgrade_database(engine, revision)
        except CommandError as e:
            if revision != 'head':
                try:
                    downgrade_database(engine, revision)
                except CommandError as e:
                    echo(e, file=sys.stderr)
                    raise SystemExit(1)
            else:
                echo(e, file=sys.stderr)
                raise SystemExit(1)


@cli.command()
@argument('service')
@config
def sync(service):  # FIXME available service listing
    """Sync to services."""
    try:
        sync = import_string('cliche.services.' + service + ':sync')
    except ImportError:
        echo('There is no such service \'{}\' suitable for synchronization.'
             .format(service),
             file=sys.stderr)
    else:
        sync.delay()


@cli.command()
@config
def align():
    """Align database"""
    alignment()


@cli.command()
@config
def shell():
    """Run a Python shell inside Flask application context."""
    with flask_app.test_request_context():
        context = dict(app=_request_ctx_stack.top.app)

        # Use basic python shell
        code.interact(local=context)


@cli.command()
@option('--host', '-h')
@option('--port', '-p', type=int)
@option('--threaded', is_flag=True)
@option('--processes', type=int, default=1)
@option('--passthrough-errors', is_flag=True)
@option('--debug/--no-debug', '-d/-D', default=None,
        help='enable the Werkzeug debugger'
             ' (DO NOT use in production code)')
@option('--reload/--no-reload', '-r/-R', default=None,
        help='monitor Python files for changes'
             ' (not 100% safe for production use)')
@config
def runserver(host, port, threaded, processes,
              passthrough_errors, debug, reload):
    """Run the Flask development server i.e. app.run()"""

    if flask_app.debug:
        # scss compile automatically in debug mode
        flask_app.wsgi_app = SassMiddleware(flask_app.wsgi_app, {
            'cliche.web': ('static/sass', 'static/css', '/static/css')
        })

    if debug is None:
        debug = flask_app.debug
    if reload is None:
        reload = flask_app.debug

    flask_setup_sentry()

    flask_app.run(host=host,
                  port=port,
                  debug=debug,
                  use_debugger=debug,
                  use_reloader=reload,
                  threaded=threaded,
                  processes=processes,
                  passthrough_errors=passthrough_errors)


@cli.command()
@config
def dummy():
    """Generate dummy data for test."""

    tropes = dict()
    works = set()

    def make_work(name, media_type):
        work = Work(media_type=media_type)
        work.names.update({
            Name(
                nameable=work,
                name=name,
                locale=HashableLocale.parse('en_US')
            )
        })
        works.add(work)
        return work

    def add_trope(name):
        if not tropes.get(name):
            tropes[name] = Trope(name=name)

    def get_trope(name):
        add_trope(name)
        return tropes[name]

    def get_tropes(names):
        res = set()
        for name in names:
            res.add(get_trope(name))
        return res

    lor = make_work('The Lord of the Rings', 'Film')
    lor.tropes.update(get_tropes({
        'Come with Me If You Want to Live',
        'Friends All Along',
        'I Lied',
    }))

    commando = make_work('Commando', 'Film')
    commando.tropes.update(get_tropes({
        'Badass',
        'The Dragon',
        'I Lied',
        'One-Man Army',
    }))

    zombieland = make_work('Zombieland', 'Film')
    zombieland.tropes.update(get_tropes({
        'Action Duo',
        'Cool Car',
        'One-Man Army',
        'Zombie Infectee',
    }))

    resident_evil = make_work('Resident Evil', 'Film')
    resident_evil.tropes.update(get_tropes({
        'Action Girl',
        'Evil Elevator',
        'Take a Third Option',
        'Zombie Infectee',
    }))

    titanic = make_work('Titanic', 'Film')
    titanic.tropes.update(get_tropes({
        'Action Girl',
        'Badass',
        'The Dragon',
        'Take a Third Option',
        'MacGuffin',
    }))

    man_in_black = make_work('Men in Black', 'Film')
    man_in_black.tropes.update(get_tropes({
        'Cool Car',
        'Creator Cameo',
        'The Dog Is an Alien',
        'MacGuffin',
        'Secret Test',
    }))

    the_wizard_of_oz = make_work('The Wizard of Oz', 'Film')
    the_wizard_of_oz.tropes.update(get_tropes({
        'Adult Fear',
        'Cool Horse',
        'Kick the Dog',
        'MacGuffin',
    }))

    the_amazing_spider_man = make_work('The Amazing Spider-Man', 'Film')
    the_amazing_spider_man.tropes.update(get_tropes({
        'Adult Fear',
        'Big Eater',
        'Byronic Hero',
        'Kick the Dog',
    }))

    v_for_vendetta = make_work('V for Vendetta', 'Film')
    v_for_vendetta.tropes.update(get_tropes({
        'After the End',
        'The Faceless',
        'Byronic Hero',
        'Secret Test',
        'You Are Number Six',
    }))

    stardust = make_work('Stardust', 'Film')
    stardust.tropes.update(get_tropes({
        'Black Comedy',
        'Blue Blood: Literally',
        'Terrible Trio',
        'You Are Number Six',
    }))

    monty_pythons_the_meaning_of_life = \
        make_work("Monty Python's The Meaning of Life", 'Film')
    monty_pythons_the_meaning_of_life.tropes.update(get_tropes({
        'Badass Grandpa',
        'Black Comedy',
        'Self-Deprecation',
        'Stupid Boss',
    }))

    die_hard = make_work('Die Hard', 'Film')
    die_hard.tropes.update(get_tropes({
        'Badass Grandpa',
        'The Dragon',
        'The Driver',
        'Secret Test',
    }))

    captain_america_the_first_avenger = \
        make_work('Captain America: The First Avenger', 'Film')
    captain_america_the_first_avenger.tropes.update(get_tropes({
        'Action Girl',
        'Cool Bike',
        'Cool Boat',
        'Cool Guns',
        'Cool Helmet',
        'Cool Plane',
        'Cool Car',
        'Fake Ultimate Hero',
        'Secret Test',
    }))

    maverick = make_work('Maverick', 'Film')
    maverick.tropes.update(get_tropes({
        'Fake Ultimate Hero',
        'Friends All Along',
        'My Favorite Shirt',
        'Take My Hand',
    }))

    the_matrix = make_work('The Matrix', 'Film')
    the_matrix.tropes.update(get_tropes({
        'All Just a Dream',
        'Bullet Time',
        'Heroic Sacrifice',
        'My Favorite Shirt',
        'Take My Hand',
        'Use Your Head',
    }))

    the_terminator = make_work('The Terminator', 'Film')
    the_terminator.tropes.update(get_tropes({
        'Come with Me If You Want to Live',
        'Heroic Sacrifice',
        'Kick the Dog',
        'What Year Is This?',
    }))

    jumanji = make_work('Jumanji', 'Film')
    jumanji.tropes.update(get_tropes({
        'Adult Fear',
        'Badass',
        'Deus ex Machina',
        'Heroic Sacrifice',
        'What Year Is This?',
    }))

    independence_day = make_work('Independence Day', 'Film')
    independence_day.tropes.update(get_tropes({
        'Alien Invasion',
    }))

    naruto = make_work('Naruto', 'Anime')
    naruto.tropes.update(get_tropes({
        "Early-Bird Cameo",
        "Early Installment Weirdness",
        "Easily-Distracted Referee",
        "Easily Forgiven",
        "Eat the Dog",
        "Egocentric Team Naming",
        "Eldritch Abomination",
        "Eldritch Location",
        "Elegant Gothic Lolita",
        "Elemental Rock-Paper-Scissors",
        "Elemental Shapeshifter",
        "Elseworlds",
        "Emotional Bruiser",
        "Empathic Environment",
        "Empowered Badass Normal",
        "Ending Theme",
        "End of an Age / Dawn of an Era",
        "The End of the World as We Know It",
        "The End... Or Is It?",
        "Enemy Civil War",
        "Enemy Mine",
        "Engineered Public Confession",
        "Entertainingly Wrong",
        "The Epic",
        "Equal-Opportunity Evil",
        "Establishing Character Moment",
        "Eternal Hero",
        "Evasive Fight Thread Episode",
        "Even Evil Has Standards",
        "Even the Girls Want Her",
        "Even the Guys Want Him",
        "Everybody Lives",
        "Everything's Better with Dinosaurs",
        "Everything's Better with Princesses",
        "Everything's Better with Spinning",
        "Everything's Even Worse with Sharks",
        "Everything's Funkier with Disco",
        "Evil Counterpart",
        "Evilutionary Biologist",
        "Evil Old Folks",
        "Evil Weapon",
        "Evolving Credits",
        "Exact Words",
        "Exaggerated Trope",
        "Gag Boobs",
        "Gag Nose",
        "Gambit Roulette",
        "Game-Breaking Injury",
        "Game Changer",
        "Gasshole",
        "Gate Guardian",
        "Gayborhood",
        "Gender Bender",
        "Gender Misdirection",
        "General Ripper",
        "Generic Cuteness",
        "Genocide from the Inside",
        "Genre Blind",
        "Genre Savvy",
        "Gentle Giant",
        "Get A Hold Of Yourself Man",
        "Getting Crap Past the Radar",
        "Giant Equals Invincible",
        "Giant Feet Of Stomping",
        "Giant Mook",
        "Girl on Girl Is Hot",
        "Giving Them the Strip",
        "Give Me a Sword",
        "A God Am I",
        "God Created Canon Foreigner",
        "Godiva Hair",
        "Godly Sidestep",
        "Godzilla Threshold",
        "Gondor Calls for Aid",
        "Gonk",
        "Good Is Not Nice",
        "Good Is Not Soft",
        "The Good King",
        "Go Out with a Smile",
        "Gory Discretion Shot",
        "Gosh Dang It to Heck!",
        "Gosh Hornet",
        "The Government",
        "Government Conspiracy",
        "Grail in the Garbage",
        "Gratuitous English",
        "Gratuitous French",
        "Gratuitous Italian",
        "Grave Robbing",
        "Gravity Sucks",
        "Green Lantern Ring",
        "Groin Attack",
        "Guns Akimbo",
        "Guns Are Worthless",
        "Gut Punch",
        "Hailfire Peaks",
        "Hammered into the Ground",
        "Hammerspace",
        "Ham-to-Ham Combat",
        "Hand Blast",
        "Handicapped Badass",
        "Handsome Lech",
        "Hanging Judge",
        "Hannyabal Lecture",
        "Happy Dance",
        "Happy Rain",
        "Harmless Freezing",
        "He's Back",
        "He Knows Too Much",
        "Heart Is an Awesome Power",
        "Heavy Sleeper",
        "Heavy Voice",
        "Heel-Face Turn",
        "Hero Antagonist",
        "Heroic BSOD",
        "Heroic RROD",
        "Heroic Sacrifice",
        "Heroic Spirit",
        "Hero of Another Story",
        "Hero Killer",
        "Heterosexual Life-Partners",
        "He Who Fights Monsters",
        "He Who Must Not Be Seen",
        "High Fantasy",
        "High-Pressure Blood",
        "Hilariously Abusive Childhood",
        "Hit-and-Run Tactics",
        "Hoist by His Own Petard",
        "Holding Hands",
        "Hollywood Evolution",
        "Hollywood Healing",
        "Hollywood Magnetism",
        "Hollywood Voodoo",
        "Home Field Advantage",
        "Honor Before Reason",
        "Homage",
        "Hook Hand",
        "Hope Spot",
        "Horned Humanoid",
        "Hostile Weather",
        "Hot-Blooded",
        "Hot Fishman On Giant Action",
        "How Do I Shot Web?",
        "Huge Girl Tiny Guy",
        "Humans Are the Real Monsters",
        "Human Doorstop",
        "Human Popsicle",
        "Human Resources",
        "Humongous Mecha",
        "Hurricane of Puns",
        "The Hyena",
        "Hyperspace Arsenal",
        "Hyperspace Mallet",
        "Hypocritical Humor",
        "Hypno Fool",
        "I Am Not Left-Handed",
        "I Am Not Weasel",
        "I Am Your Opponent",
        "I Can Rebuild Myself",
        "I Can Still Fight",
        "I Can't Do This by Myself",
        "Icarus Allusion",
        "Iconic Outfit",
        "An Ice Person",
        "Identical Stranger",
        "Identity Concealment Disposal",
        "Idiot Ball",
        "Idiot Hair",
        "Idiot Hero",
        "Ignored Enemy",
        "I Have No Son",
        "I Knew It",
        "I Know You Are In There Somewhere Fight",
        "I Let You Win",
        "I Like Those Odds",
        "Ill Girl",
        "I'm a Humanitarian",
        "Imagine Spotting",
        "Immunity Disability",
        "Impact Silhouette",
        "Impaled with Extreme Prejudice",
        "Implacable Man",
        "Impossible Hourglass Figure",
        "Impossibly Cool Clothes",
        "Impoverished Patrician",
        "Improbable Aiming Skills",
        "Incendiary Exponent",
        "Incorruptible Pure Pureness",
        "Incredibly Conspicuous Drag",
        "Incredibly Lame Pun",
        "Ineffectual Sympathetic Villain",
        "Inelegant Blubbering",
        "Infant Immortality",
        "Info Drop",
        "Inner Monologue Conversation",
        "Innocuously Important Episode",
        "Insane Troll Logic",
        "Inspirational Insult",
        "Instant Armor",
        "Instant Dogend",
        "Instant Knots",
        "Instant Waking Skills",
        "Instrument of Murder",
        "Intangible Man",
        "Interacting with Shadow",
        "Intergenerational Friendship",
        "Internal Reveal",
        "In the Blood",
        "Intrinsic Vow",
        "Inverse Law of Complexity to Power",
        "Invisibility",
        "Invisible Jerkass",
        "Involuntary Group Split",
        "Ironic Echo",
        "Irrational Hatred",
        "Ironic Hell",
        "Irrevocable Order",
        "Is It Always Like This?",
        "Island of Mystery",
        "It Amused Me",
        "It Runs on Nonsensoleum",
        "It's Personal",
        "I Was Quite a Looker",
        "I Will Wait for You",
        "I Would Say If I Could Say",
        "Invented Invalid",
        "The Jailbait Wait",
        "Jade-Colored Glasses",
        "Japanese Spirit",
        "Jaw Drop",
        "Jerkass Façade",
        "Jerk with a Heart of Gold",
        "Jesus Taboo",
        "Joker Jury",
        "Justice Will Prevail",
        "Just Following Orders",
        "Just Friends",
        "Just One Man",
        "LEGO Genetics",
        "Limited Wardrobe",
        "Line-of-Sight Name",
        "Living MacGuffin",
        "Living Weapon",
        "Loads and Loads of Characters",
        "Local Hangout",
        "Longest Pregnancy Ever",
        "Loophole Abuse",
        "Losing Your Head",
        "Love Hurts",
        "Love Letter",
        "Luke, I Am Your Father",
        "Mandatory Unretirement",
        "Magical Eye",
        "Magic by Any Other Name",
        "Mama Bear",
        "Man Behind the Man",
        "Manly Tears",
        "Master-Apprentice Chain",
        "Me's a Crowd",
        "Meaningful Funeral",
        "Meaningful Name",
        "Mentor Occupational Hazard",
        "Messianic Archetype",
        "Meteor Move",
        "Mind Rape",
        "Mind Screw",
        "Misery Builds Character",
        "Monster Shaped Mountain",
        "Multiple-Tailed Beast",
        "Mundane Utility",
        "My God, What Have I Done?",
        "Never a Self-Made Woman",
        "New Powers as the Plot Demands",
        "Nice Job Breaking It, Hero",
        "Nice Job Fixing It, Villain",
        "Ninja",
        "Ninja Log",
        "Nobody Poops",
        "Nonhumans Lack Attributes",
        "The Nose Bleed",
        "Not a Date / She Is Not My Girlfriend",
        "Not Cheating Unless You Get Caught",
        "Not Even Human",
        "Nothing but Skin and Bones",
        "Not Just a Tournament",
        "Not Quite Dead",
        "Not So Different",
        "Not So Stoic",
        "Nothing Is the Same Anymore",
        "Oblivious Mockery",
        "Oddly Small Organization",
        "Official Couple",
        "Offscreen Moment of Awesome",
        "Oh, Crap",
        "One Extra Member",
        "One-Winged Angel",
        "Only a Flesh Wound",
        "The Only One Allowed to Defeat You",
        "Organ Theft",
        "Orphanage of Love",
        "Our Zombies Are Different",
        "Out of Focus",
        "Overshadowed by Awesome",
        "Papa Wolf",
        "Parental Abandonment",
        "Passion Is Evil",
        "Person of Mass Destruction",
        "Phlebotinum-Handling Requirements",
        "The Pirates Who Don't Do Anything",
        "Playing with Fire",
        "Please Don't Leave Me",
        "Plot Armor",
        "The Plot Reaper",
        "Plot Tumor",
        "Police Are Useless",
        "Power Makes Your Hair Grow",
        "The Power of Friendship",
        "The Power of Hate",
        "The Power of Love",
        "Powers as Programs",
        "Protagonist-Centered Morality",
        "Protagonist Journey to Villain",
        "Psycho Rangers",
        "A Pupil of Mine Until He Turned to Evil",
        "Punny Name",
        "Random Power Ranking",
        "Rank Up",
        "Rays from Heaven",
        "Razor Sharp Hand",
        "Reality Ensues",
        "Reality Is Unrealistic",
        "Reality Warper",
        "Recruited From The Gutter",
        "Redemption Equals Death",
        "Red Oni, Blue Oni",
        "Refuge in Audacity",
        "Red Shirt Army",
        "Red String of Fate",
        "Reformed But Not Tamed",
        "Reptiles Are Abhorrent",
        "Rescue Romance",
        "The Rest Shall Pass",
        "Retcon",
        "Reusable Lighter Toss",
        "The Reveal",
        "Right Makes Might",
        "Roofhopping",
        "Rousing Speech",
        "Rousseau Was Right",
        "Rule of Symbolism",
        "Rummage Sale Reject",
        "Running Gagged",
        "Sacrificial Revival Spell",
        "Sadistic Choice",
        "Sarutobi Sasuke",
        "Save The World Climax",
        "Saving the Orphanage",
        "Say My Name",
        "School Saved My Life",
        "Schizo Tech",
        "Sci Fi Fantasy Writers Have No Sense Of Scale",
        "Sealed Evil in a Can",
        "Self-Duplication",
        "Self Healing Phlebotinum",
        "Sempai/Kohai",
        "Series Continuity Error",
        "Serpent of Immortality",
        "Sexposition",
        "Shared Family Quirks",
        "Ship Sinking",
        "Ship Tease",
        "Shoo Out the Clowns",
        "Shout-Out",
        "Shoot the Dog",
        "Shoot the Hostage",
        "Shown Their Work",
        "Shut Up, Hannibal!",
        "Sins of Our Fathers",
        "Skeleton Government",
        "Skyscraper City",
        "Slap Yourself Awake",
        "Slave Brand",
        "Smash The Symbol",
        "Smitten Teenage Girl",
        "The Smurfette Principle",
        "Snap to the Side",
        "Sneezing",
        "Social Services Does Not Exist",
        "Sorting Algorithm of Evil",
        "The Spartan Way",
        "Spell Levels",
        "Spiritual Successor",
        "Spoiler",
        "Spot the Imposter",
        "Spy Catsuit",
        "Standard Evil Organization Squad",
        "Start of Darkness",
        "Start X to Stop X",
        "Step into the Blinding Fight",
        "Stock Ninja Weaponry",
        "Summon Magic",
        "Super-Powered Evil Side",
        "Super Reflexes",
        "Supernatural Martial Arts",
        "Superpowerful Genetics",
        "Take a Third Option",
        "Take Over the World",
        "Take That, Audience!",
        "Taking the Bullet",
        "Talk to the Fist",
        "Talking Is a Free Action",
        "Talking the Monster to Death",
        "Tears of Joy",
        "Teen Genius",
        "Tempting Fate",
        "That's No Moon!",
        "There Are No Therapists",
        "There Is No Kill Like Overkill",
        "This Is Something He's Got to Do Himself",
        "Those Two Guys",
        "Throwing the Fight",
        "Tickle Torture",
        "Tiger Versus Dragon",
        "Time Skip",
        "To Be a Master",
        "Took a Level in Badass",
        "Tournament Arc",
        "Trail of Bread Crumbs",
        "Training The Gift Of Magic",
        "Training the Peaceful Villagers",
        "Trash Talk",
        "Traumatic Superpower Awakening",
        "Triang Relations",
        "Troll",
        "True Companions",
        "Try Not to Die",
        "Tsundere",
        "Tunnel King",
        "Turtle Island",
        "Two Guys and a Girl",
        "Two Scenes, One Dialogue",
        "Unrequited Love Switcheroo",
        "Unstoppable Rage",
        "Unwitting Instigator of Doom",
        "Used to Be a Sweet Kid",
        "Utopia Justifies the Means",
        "Vein-O-Vision",
        "Vengeance Feels Empty",
        "Vicious Cycle",
        "Viewers Are Goldfish",
        "Villain Override",
        "Vomit Indiscretion Shot",
        "Walk on Water",
        "War Arc",
        "The War to End All Wars",
        "Warrior Therapist",
        "Wave Motion Gun",
        "Way Past the Expiration Date",
        "Weapon Tombstone",
        "Welcome Back, Traitor",
        "Well-Intentioned Extremist",
        "Wham Episode",
        "Wham Line",
        "Wham Shot",
        "What Happened to the Mouse?",
        "What the Hell, Hero?",
        "When All You Have Is a Hammer",
        "Willfully Weak",
        "Women in Refrigerators",
        "Woobie, Destroyer of Worlds",
        "The Worf Barrage",
        "The Worf Effect",
        "Worf Had the Flu",
        "World Domination",
        "World Half Full",
        "World of Badass",
        "World Of Card Board Speech",
        "World of Ham",
        "World of Silence",
        "Would Hit a Girl",
        "Wrap It Up",
        "X-Ray Vision",
        "Yoyo Plot Point",
        "You Are Already Dead",
        "You Are Not Alone",
        "You Know The One",
        "Your Mind Makes It Real",
    }))

    onepiece = make_work('One Piece', 'Anime')
    onepiece.tropes.update(get_tropes({
        "Abhorrent Admirer",
        "The Abridged Series",
        "Absolute Cleavage",
        "Accidental Marriage",
        "Achievements in Ignorance",
        "Achilles in His Tent",
        "Acquired Poison Immunity",
        "Action Bomb",
        "Action Girl",
        "Action Survivor",
        "Actor Allusion",
        "Actual Pacifist",
        "Adaptation Distillation",
        "Adaptation Dye-Job",
        "Adaptation Expansion",
        "Adaptation Induced Plot Hole",
        "Addiction Powered",
        "Adipose Rex",
        "Adult Fear",
        "Advanced Ancient Acropolis",
        "Advancing Wall of Doom",
        "Adventure Series",
        "Adventure Towns",
        "Aerith and Bob",
        "Affably Evil",
        "Afro Asskicker",
        "Agent Peacock",
        "Air Jousting",
        "The Alcatraz",
        "The Alcoholic",
        "All Amazons Want Hercules",
        "All of the Other Reindeer",
        "All There in the Manual",
        "All Women Are Lustful",
        "The Aloner",
        "Aloof Older Brother",
        "Alpha Strike",
        "Alternative Foreign Theme Song",
        "Always a Bigger Sea King",
        "Always Chaotic Evil",
        "Always Someone Better",
        "A Million Is a Statistic",
        "Amusing Injuries",
        "And I Must Scream",
        "Angrish",
        "Animal Motifs",
        "Animal Talk",
        "Animate Dead",
        "Animation Bump",
        "Animesque",
        "Anime Theme Song",
        "Animorphism",
        "Annoying Arrows",
        "Arbitrary Skepticism",
        "Arc Number",
        "Arc Villain",
        "Arc Words",
        "Arch-Enemy",
        "Aristocrats Are Evil",
        "Armor-Piercing Slap",
        "Arrogant Kung-Fu Guy",
        "Artificial Human",
        "Art Attacker",
        "Art Evolution",
        "Art Shift",
        "Art-Style Dissonance",
        "Ascended Fanboy",
        "Asleep for Days",
        "As Lethal as It Needs to Be",
        "As Long as It Sounds Foreign",
        "As Long As There Is One Man",
        "Astonishingly Appropriate Appearance",
        "Attack Reflector",
        "Author Appeal",
        "Author Avatar",
        "Authority Equals Asskicking",
        "Author Appeal",
        "Autocannibalism",
        "Award Bait Song",
        "Awesome McCoolname",
        "Awesomeness Is a Force",
        "Ax-Crazy",
        "An Axe to Grind",
        "Back Story",
        "Back-to-Back Badasses",
        "Badass",
        "Badass Adorable",
        "Badass Boast",
        "Badass Bookworm",
        "Badass Crew",
        "Badass Family",
        "Badass Grandpa",
        "Badass in a Nice Suit",
        "Badass in Distress",
        "Badass Longcoat",
        "Badass Mustache",
        "Badass Normal",
        "Baddie Flattery",
        "Bad Liar",
        "Bait the Dog",
        "Balance of Power",
        "Balloon Belly",
        "Bare Your Midriff",
        "The Baroness",
        "Base on Wheels",
        "Bastard Girlfriend",
        "Batman Gambit",
        "Battle Interrupting Shout",
        "Battle Tops",
        "Battle Trophy",
        "Be Careful What You Wish For",
        "Beam Spam",
        "Bears Are Bad News",
        "Beard of Evil",
        "Beast Man",
        "Beat Them at Their Own Game",
        "Beauty Is Never Tarnished",
        "Because You Were Nice to Me",
        "The Bechdel Test",
        "Behemoth Battle",
        "Believing Their Own Lies",
        "Bequeathed Power",
        "Berserk Button",
        "Best Her to Bed Her",
        "Better to Die Than Be Killed",
        "Beware the Nice Ones",
        "Beyond the Impossible",
        "BFS",
        "Big Bad",
        "Big Bad Ensemble",
        "Big Ball of Violence",
        "Big Brother Instinct",
        "Big Brother Is Watching",
        "Big Brother Mentor",
        "Big Bulky Bomb",
        "Big Creepy-Crawlies",
        "Big Damn Heroes",
        "Big Eater",
        "Big Entrance",
        "Bigger Bad",
        "Big Good",
        "Bilingual Bonus",
        "Billing Displacement",
        "Bishōnen",
        "Bishonen Line",
        "Blank White Eyes",
        "Blessed with Suck",
        "Blinding Bangs",
        "Blood Brothers",
        "Bloodier and Gorier",
        "Blood Knight",
        "Bloodless Carnage",
        "Blood Upgrade",
        "Bloody Hilarious",
        "Bloody Murder",
        "Blush Sticker",
        "Boisterous Bruiser",
        "Boke and Tsukkomi Routine",
        "Bond Villain Stupidity",
        "Boobs of Steel",
        "Book Ends",
        "Bootstrapped Leitmotif",
        "Bouncing Battler",
        "Bowdlerise",
        "Boxing Lessons for Superman",
        "Braids of Action",
        "Brainwashed and Crazy",
        "Break the Cutie",
        "Breaking the Fellowship",
        "Breakout Character",
        "Break Up Make Up Scenario",
        "Breast Expansion",
        "Breath Weapon",
        "Brick Joke",
        "Bring My Brown Pants",
        "Broken Bird",
        "Broke Your Arm Punching Out Cthulhu",
        "Built with LEGO",
        "Bunny-Ears Lawyer",
        "Buried Alive",
        "Burning with Anger",
        "Butt Monkey",
        "Cain and Abel and Seth",
        "Call Back",
        "Call to Agriculture",
        "Calling Your Attacks",
        "Came Back Strong",
        "Came from the Sky",
        "Camp Gay",
        "Canon Immigrant",
        "Can't Catch Up",
        "Carnival of Killers",
        "Casting a Shadow",
        "Casting Gag",
        "Catch-22 Dilemma",
        "Catchphrase",
        "Catgirl",
        "Cerebus Retcon",
        "Cerebus Rollercoaster",
        "Cerebus Syndrome",
        "Chainmail Bikini",
        "Chameleon Camouflage",
        "Character Development",
        "Charles Atlas Superpower",
        "Charlie Brown from Outta Town",
        "Chaste Hero",
        "Chekhov's Armoury\Chekhov's Army",
        "Cheerful Child",
        "Chef of Iron",
        "Cherry Blossoms",
        "The Chessmaster",
        "Children Are Innocent",
        "Child Soldiers",
        "Chilly Reception",
        "Chivalrous Pervert",
        "Chromatic Arrangement",
        "Cigar Fuse Lighting",
        "Circus of Fear",
        "City of Canals",
        "Civilized Animal",
        "Cloud Cuckoo Lander",
        "Combat Clairvoyance",
        "Combat Medic",
        "Combining Mecha",
        "Comedic Sociopathy",
        "Comically Missing the Point",
        "The Comically Serious",
        "Commedia dell'Arte",
        "Competence Zone",
        "Composite Character",
        "Compressed Adaptation",
        "Conservation of Competence",
        "Conspicuous CG",
        "Continuity Nod",
        "Continuity Porn",
        "Contrived Coincidence",
        "Convection Schmonvection",
        "Cosmopolitan Council",
        "Cool Boat",
        "Cool Old Guy",
        "Cool Train",
        "Cooperation Gambit",
        "Costume Copycat",
        "Cowardly Lion",
        "Cranial Eruption",
        "Cranium Chase",
        "Crapsaccharine World",
        "Crashing Through the Harem",
        "Crazy-Prepared",
        "Creator Cameo",
        "Creepy Cool Crosses",
        "Credits Running Sequence",
        "Criminal Doppelgänger",
        "Cross Counter",
        "Cross Dresser",
        "Crucified Hero Shot",
        "Crying Wolf",
        "Cue the Sun",
        "Culture Chop Suey",
        "Culture Clash",
        "Curb-Stomp Battle",
        "Curse That Cures",
        "Cursed with Awesome",
        "Curtains Match the Window",
        "Cut-and-Paste Translation",
        "Cut Lex Luthor a Check",
        "Cute Ghost Girl",
        "Cute Giant",
        "Cutlass Between the Teeth",
        "Cyborg",
        "Cycle of Revenge",
        "Daddy Had a Good Reason for Abandoning You",
        "Dance Battler",
        "Dance Party Ending",
        "Dangerous Forbidden Technique",
        "Dangerous Phlebotinum Interaction",
        "Dark Action Girl",
        "Darker and Edgier",
        "Dark and Troubled Past",
        "Dark Is Not Evil",
        "A Day in the Limelight",
        "Day of the Week Name",
        "The Dead Can Dance",
        "The Dead Have Eyes",
        "Deadly Upgrade",
        "Deal with the Devil",
        "Deadpan Snarker",
        "Death by Childbirth",
        "Death by Origin Story",
        "Death Glare",
        "Death World",
        "Debut Queue",
        "Decade Dissonance",
        "Declining Promotion",
        "Deconstructed Trope",
        "Defeating the Undefeatable",
        "Defeat Means Friendship",
        "Defector from Decadence",
        "Defensive Feint Trap",
        "Defrosting Ice Queen",
        "Delayed Reaction",
        "Dem Bones",
        "Demon Head",
        "Department of Redundancy Department",
        "Desert Bandits",
        "Designated Girl Fight",
        "Destroy the Abusive Home",
        "Detachment Combat",
        "Determinator",
        "Deus Exit Machina",
        "Development Gag",
        "Diabolus Ex Machina",
        "Did You Just Flip Off Cthulhu?",
        "Did You Just Punch Out Cthulhu?",
        "Didn't Think This Through",
        "Died in Your Arms Tonight",
        "Died Standing Up",
        "Dirty Old Man",
        "Disability Superpower",
        "Disappeared Dad",
        "Disney Death",
        "Disney Villain Death",
        "Distant Finale",
        "Distressed Dude",
        "The Ditz",
        "Does This Remind You of Anything?",
        "Doing In the Wizard",
        "Dojikko",
        "The Don",
        "Do Not Go Gentle",
        "Dope Slap",
        "Double Jump",
        "Dragon-in-Chief",
        "The Dreaded",
        "Driving Question",
        "Dr. Jerk",
        "Drop the Hammer",
        "Drunk with Power",
        "Drunken Master",
        "Dual Wielding",
        "Dub-Induced Plot Hole",
        "Duel to the Death",
        "Dumbass Has a Point",
        "Dumb Is Good",
        "Dumb Muscle",
        "Dying Moment of Awesome",
        "Dysfunction Junction",
        "Excited Title! Two-Part Episode Name!",
        "Experimental Archeology",
        "Exploited Immunity",
        "Expository Hairstyle Change",
        "Expository Theme Tune",
        "Expressive Hair",
        "Expy",
        "Extranormal Prison",
        "Extreme Doormat",
        "Eyes Are Mental",
        "Eye Catch",
        "Eye Shock",
        "Face Fault",
        "Facial Composite Failure",
        "Fake Defector",
        "Fake Ultimate Hero Villain",
        "Family-Friendly Firearms",
        "Family-Unfriendly Violence",
        "Fandom Nod",
        "Fanservice",
        "Fantastic Fighting Style",
        "Fantastic Ghetto",
        "Fantastic Racism",
        "Fantasy Conflict Counterpart",
        "Fantasy Counterpart Culture",
        "Fantasy Kitchen Sink",
        "Fartillery",
        "Fate Worse Than Death",
        "Failure Knight",
        "A Father to His Men",
        "Faux Symbolism",
        "Feather Boa Constrictor",
        "Feather Fingers",
        "Femme Fatale",
        "The Fettered",
        "Fiery Redhead",
        "Fighting from the Inside",
        "Filler",
        "Fire-Forged Friends",
        "Finger Twitching Revival",
        "Fish People",
        "Flashback",
        "Flash Step",
        "Flat Earth Atheist",
        "Flawed Prototype",
        "Flight",
        "Flipping the Table",
        "Floating Continent",
        "Floatingina Bubble",
        "Fluffy Tamer",
        "Flunky Boss",
        "Follow the Chaos",
        "Fountain of Youth",
        "Forgot I Couldn't Swim",
        "Foreshadowing",
        "4Kids Entertainment",
        "The Four Loves",
        "Fragile Speedster",
        "Friendly Enemy",
        "A Friend in Need",
        "Freak Out",
        "Freaky Is Cool",
        "French Cuisine Is Haughty",
        "Freudian Excuse",
        "Frickin' Laser Beams",
        "Friction Burn",
        "Friendly Enemy",
        "From Bad to Worse",
        "Full Potential Upgrade",
        "Funbag Airbag",
        "Funny Afro",
        "Fur Bikini",
    }))

    sailor_moon = make_work('Sailor Moon', 'Anime')
    sailor_moon.tropes.update(get_tropes({
        'Action Girl',
        'Dangerously Short Skirt',
        'Age Is Relative',
        'Aliens and Monsters',
        'Aliens Speaking English',
        'Alien Abduction',
        'Amazon Brigade',
        'Amnesiac Lover',
        'Amusing Injuries',
        'Anachronism Stew',
        'Annoying Younger Sibling',
        'As Long as There Is Evil',
        'Art Evolution',
        'Author Appeal',
        'Back from the Dead',
        'Belligerent Sexual Tension',
        'Brainwashed and Crazy',
        'By the Power of Grayskull!',
        'Calling Your Attacks',
        'Cats Are Magic',
        'Chastity Couple',
        'The Chosen Many',
        'Clothes Make the Legend',
        'Combined Energy Attack',
        'Cross Over',
        'Cryptic Background Reference',
        'Death Is Cheap',
        'Determinator and Plucky Girl',
        'Disc One Final Boss',
        'Distressed Dude',
        'Dress-Coded for Your Convenience',
        'Elemental Rock-Paper-Scissors',
        'Eleventh Hour Superpower',
        'The End of the World as We Know It',
        'Epileptic Trees',
        'Evil Plan',
        'Facial Markings',
        'Fairytale Wedding Dress',
        'Family-Unfriendly Death',
        'Five-Man Band',
        'The Leader',
        'The Lancer',
        'The Smart Guy',
        'The Big Guy',
        'The Heart',
        'Plucky Comic Relief',
        'The One Guy',
        'Team Pets',
        'Foolish Sibling, Responsible Sibling',
        'Foreshadowing',
        'Forgotten Phlebotinum',
        'Four Is Death',
        'Frilly Upgrade',
        'Genre Popularizer / Trope Codifier',
        'Giant Waist Ribbon',
        'A God Am I',
        'Grand Finale',
        'Gratuitous English',
        'Hair Colors',
        'Hand Blast',
        'Heroic Sacrifice',
        'Hostage for MacGuffin',
        'Human Aliens',
        'Human Resources',
        'I Just Want to Have Friends',
        'Immortality Begins at Twenty',
        'Intellectual Property Religion',
        'In the End, You Are on Your Own',
        'In the Name of the Moon',
        'Invisible Parents',
        'Invisible to Normals',
        'Kid-Appeal Character',
        'Kissing Under the Influence',
        'Large Ham',
        'Late for School',
        'Leotard of Power',
        'Light Feminine and Dark Feminine',
        'Living Memory',
        'Living Relic',
        'Local Hangout',
        'Magical Girl',
        'Magical Girl Warrior',
        'Magic Music',
        'The Woman Behind The Woman',
        'Mass Hypnosis',
        'Meaningful Name',
        'Mid-Season Upgrade',
        'Mind-Control Eyes',
        'Mind Rape',
        'Mini Dress Of Power ',
        'Mirror Morality Machine',
        'Mood Whiplash',
        'Morning Routine',
        'Mukokuseki',
        'My Significance Sense Is Tingling',
        'Mysterious Protector',
        'New Transfer Student',
        'Necessarily Evil',
        'The Nineties',
        'Official Couple',
        'Ojou Ringlets',
        'Older Alter Ego',
        'Omnicidal Maniac',
        'One Extra Member',
        'Only Six Faces',
        'Ordinary High-School Student',
        'Out-Gambitted',
        'Out-of-Clothes Experience',
        'Pantyshot',
        'Paper-Thin Disguise',
        'Parental Abandonment',
        'Pimped-Out Dress',
        'Playing with Fire',
        'Plot-Relevant Age-Up',
        'Power Gives You Wings',
        'Power Trio',
        'The Power of Love',
        'Praetorian Guard',
        'Pretty in Mink',
        'Prophetic Names',
        'Protagonist Power-Up Privileges',
        'A Protagonist Shall Lead Them',
        'The Psycho Rangers',
        'Public Domain Artifact',
        'Puppy-Dog Eyes',
        'Put on a Bus',
        'Quirky Miniboss Squad',
        'Really Gets Around',
        'Reincarnation',
        'Reincarnation Romance',
        'Requisite Royal Regalia',
        'Reset Button',
        'Roofhopping',
        'Rules of Orphan Economics',
        'Sailor Earth',
        'Science Marches On',
        'Sealed Cast in a Multipack',
        'Sealed Evil in a Can',
        'Shoo Out the Clowns',
        'Silly Rabbit, Cynicism Is for Losers!',
        'Simple Yet Opulent',
        'Slapstick Knows No Gender',
        'Sliding Scale of Idealism Versus Cynicism',
        'So Last Season',
        'Sorting Algorithm of Evil',
        'Stab the Sky',
        'Stars Are Souls',
        'Stealth Hi/Bye',
        'Story Arc',
        'Stupid Sexy Flanders',
        'Super Mode',
        'Talking Is a Free Action',
        'Team Spirit',
        'Theme Naming',
        'This Is Unforgivable!',
        'Villain Teleportation',
        'Wake Up, Go to School, Save the World',
        'What the Hell, Hero?',
        'Wing Pull',
        'Winged Humanoid',
        'Winter Royal Lady',
        'Woobie, Destroyer of Worlds',
        'The World Is Always Doomed',
        'Write Who You Know',
        'X Meets Y',
        'Xenafication',
        'You Gotta Have Blue Hair',
        'are normal human colors',
        'You Have Failed Me',
    }))

    speed_racer = make_work('Speed Racer', 'Anime')
    speed_racer.tropes.update(get_tropes({
        'The Abridged Series',
        'Adaptation Dye-Job',
        'Adaptation Name Change',
        'Acrofatic',
        'Action Girl',
        'All There in the Manual',
        'Almost Out of Oxygen',
        'Alternate Continuity',
        'Badass Driver',
        'Badass Family',
        'Bat Deduction',
        'The Big Race',
        'Black Knight',
        'Bragging Theme Tune',
        'Brats with Slingshots',
        'Car Fu',
        'Cool Car',
        'Convection Schmonvection',
        'Chick Magnet',
        'Cut Short',
        'Dub Name Change',
        'Every Car Is a Pinto',
        'Expy',
        'Family-Unfriendly Death',
        'Forgotten Phlebotinum',
        'Free Wheel',
        'Genius Bruiser',
        'Good Bad Translation',
        'Grievous Bottley Harm',
        'Hong Kong Dub',
        'Identical Stranger',
        'Invincible Hero',
        'It Gets Easier',
        'Large Ham',
        'Limited Animation',
        'Little Stowaway',
        'Long Lost Sibling',
        'Man of a Thousand Voices',
        'Motor Mouth',
        'Mr. Fanservice',
        'Ninja',
        'Non-Human Sidekick',
        'One-Man Army',
        'One, Two, Three, Four, Go!',
        'Papa Wolf',
        'Pink Means Feminine',
        'Pop the Tires',
        'Precision F-Strike',
        'Trixie',
        'Speed',
        'Punny Name',
        'Reasonable Authority Figure',
        'The Scrooge',
        'Serious Business',
        'Spiked Wheels',
        'Steven Ulysses Perhero',
        'Switching To GEICO',
        'Tagalong Kid',
        'Transforming Vehicle',
        'Weaponized Car'
    }))

    frozen = make_work('Frozen', 'Film')
    frozen.tropes.update(get_tropes({
        'Accidental Misnaming',
        'Action Girl',
        'Action Insurance Gag',
        'Act Of True Love',
        'Adaptation Induced Plot Hole',
        'Adult Fear',
        'Afraid of Their Own Strength',
        'Airplane Arms',
        'Alertness Blink',
        'All There in the Manual',
        'All There in the Script',
        'All Trolls Are Different',
        'Almost Kiss',
        'Always Save the Girl',
        'Amazingly Embarrassing Parents',
        'American Kirby Is Hardcore',
        'An Aesop',
        'Anachronism Stew',
        'Animal Motifs',
        'Animated Musical',
        'Annoying Arrows',
        'Anti-Climax',
        'Arc Symbol',
        'Artistic License - Physics',
        'Audible Sharpness',
        'Award Bait Song',
        'Awesome Moment of Crowning',
        'Badass Boast',
        'Bait and Switch',
        'Bait-and-Switch Comparison',
        'Banister Slide',
        'Barehanded Blade Block',
        'Beast and Beauty',
        'The Bechdel Test',
        'Betty and Veronica',
        'Beware the Nice Ones',
        'Beyond the Impossible',
        'The Big Damn Kiss',
        'Big "NO!"',
        'Roughly translated, the lyrics are',
        'Black Comedy',
        'Blessed with Suck',
        'Blonde, Brunette, Redhead',
        'Bond Villain Stupidity',
        'Braids of Action',
        'Break His Heart to Save Him',
        'Break the Cutie',
        'Breakout Character',
        'Bullying a Dragon',
        'The Call Knows Where You Live',
        'The Cameo',
        'Casual Danger Dialogue',
        'Church of Saint Genericus',
        'Circle of Standing Stones',
        'Closed Door Rapport',
        'Colour Motif',
        'Comically Missing the Point',
        'Conspicuous Gloves',
        'Conveniently an Orphan',
        'Costume Porn',
        'Counterpoint Duet',
        'Crash-Into Hello',
        'Creator Cameo',
        'Credits Gag',
        'Crowd Song',
        'Cue the Sun',
        'Cup Holders',
        'Curse Escape Clause',
        'Cuteness Overload/Cuteness Proximity',
        'Dagwood Sandwich',
        'Damsel in Distress',
        'Dance Party Ending',
        'Darker and Edgier',
        'Dark Reprise',
        'Dead Unicorn Trope',
        'Decon-Recon Switch',
        'Decoy Antagonist',
        'Description Cut',
        'Detached Sleeves',
        'The Determinator',
        'Died in Your Arms Tonight',
        'Did You Actually Believe?',
        'Disney Acid Sequence',
        'Disneyfication',
        'Disney Princess',
        'Disproportionate Retribution',
        'Dodgy Toupee',
        'Double Aesop',
        'Double Meaning Title',
        'Dramatic Wind',
        'Dreamworks Face',
        'Dual Meaning Chorus',
        'Dying Alone',
        'Earn Your Happy Ending',
        'Emotional Powers',
        'Emotionless Girl',
        'Endless Winter',
        'Every Car Is a Pinto',
        'Evil Cannot Comprehend Good',
        'Evil Old Folks',
        'Evil Prince',
        'Evil Virtues',
        'Failsafe Failure',
        'Fairy Tale',
        'Fake Ultimate Hero',
        'Falling Chandelier of Doom',
        'Falling in Love Montage',
        'Family Business',
        'Fantasy Counterpart Culture',
        'Fantasy Gun Control',
        'Feminist Fantasy',
        'First Girl Wins',
        'Fisher Queen',
        'Foolish Sibling, Responsible Sibling',
        'potential love interests',
        'The Four Chords of Pop',
        'The Four Loves',
        'Literally',
        'Freudian Excuse',
        'Freudian Slip',
        'Friendless Background',
        'Get Out',
        'Gilded Cage',
        'Girlish Pigtails',
        'Good Hair, Evil Hair',
        'Good Parents',
        'Go Mad from the Isolation',
        'Graceful in Their Element',
        'Grim Up North',
        'Hair Decorations',
        'Happily Adopted',
        'Harmless Freezing',
        'He Was Right There All Along',
        'Hide Your Pregnancy',
        'Hollywood Law',
        'Hollywood Personality Disorders',
        'disorder',
        'Hood Ornament Hottie',
        'How Do I Shot Web?',
        'Humans Are Bastards',
        'Hurricane of Puns',
        'I Am a Monster',
        'I Am Becoming Song',
        'I Just Want to Be Normal',
        'I Want My Beloved to Be Happy',
        'Ice Palace',
        'An Ice Person',
        'Ice Queen',
        'If Only You Knew',
        'Incorruptible Pure Pureness',
        'In Name Only',
        'In The Style Of',
        'Ink-Suit Actor',
        'Instant Ice, Just Add Cold',
        'Instrument of Murder',
        'It Is Pronounced Tro-PAY',
        'Jumping Off the Slippery Slope',
        'Just Between You and Me',
        'Lantern Jaw of Justice',
        'Laser-Guided Amnesia',
        'Late-Arrival Spoiler',
        'Laughably Evil',
        'Leave the Two Lovebirds Alone',
        'Left for Dead',
        'Leitmotif',
        'Let no Crisis Go to Waste',
        'Letting Her Hair Down',
        'Literally Shattered Lives',
        'Literal-Minded',
        'Littering Is No Big Deal',
        'Locked into Strangeness',
        'Lonely Piano Piece',
        'Lonely Rich Kid',
        'Love at First Sight',
        'Love Interest Traitor',
        'Love Theme',
        'Love Triangle',
        'Love Revelation Epiphany',
        'Lyrical Dissonance',
        'Mad God',
        'Major Injury Underreaction',
        'Manipulative Bastard',
        'Manly Man And Sensitive Guy',
        'Manly Tears',
        'Massive Numbered Siblings',
        'Match Cut',
        'Meaningful Echo',
        'Meaningful Name',
        'Meet Cute',
        'Metaphorically True',
        'A Minor Kidroduction',
        'Moral Event Horizon',
        'Motif',
        'Muggle Born of Mages',
        'Murder By Inaction',
        'My God, What Have I Done?',
        'Recursively',
        'Nature Is Not Nice',
        'Never Say "Die"',
        'at mountain climbing',
        'Nice Job Fixing It, Villain',
        'Nice Guy',
        'Nice to the Waiter',
        'Nightmare Fetishist',
        'Noble Male, Roguish Male',
        'No Body Left Behind',
        'No Cartoon Fish',
        'No Endor Holocaust',
        'No Flow in CGI',
        'Non-Human Sidekick',
        'No Ontological Inertia',
        'No Sell',
        'No Sense of Personal Space',
        'Norse by Norsewest',
        'Odd Name Out',
        'Official Couple',
        'Oh, Crap',
        'Only Six Faces',
        'One Head Taller',
        'One Steve Limit',
        'One-Winged Angel',
        'The Outside World',
        'Overprotective Dad',
        'Painful Transformation',
        'Parent Service',
        'Older Sister Marriage Veto',
        'Parental Neglect',
        'Pent Up Power Peril',
        'Perpetual Storm',
        'Person of Mass Destruction',
        'Personal Raincloud',
        'Pimped Out Cape',
        'Pimped-Out Dress',
        'Please Wake Up',
        'Plucky Comic Relief',
        'Plucky Girl',
        'Plummet Perspective',
        'Polite Villains, Rude Heroes',
        'The Poll',
        'The Power of Love',
        'Pragmatic Villainy',
        'Princesses Rule',
        'Prolonged Prologue',
        'Psychoactive Powers',
        'Purple Is Powerful',
        'Rage Breaking Point',
        'Raised by Wolves',
        'Randomly Gifted',
        'Rant Inducing Slight',
        'Reality Ensues',
        'Reality Is Unrealistic',
        'Both',
        'Both',
        'Rebellious Princess',
        'Recognition Failure',
        'Red Oni, Blue Oni',
        'Required Secondary Powers',
        'Requisite Royal Regalia',
        'Rich Suitor, Poor Suitor',
        'Riddle for the Ages',
        'Right Behind Me',
        'Right for the Wrong Reasons',
        'Rule of Glamorous',
        'Rule of Symbolism',
        'Rule 63',
        'Sadistic Choice',
        'Sanity Slippage Song',
        'And one thought crystallizes like an icy blast',
        'Savage Wolves',
        'Savvy Guy, Energetic Girl',
        'Say My Name',
        'Scenery Porn',
        'Second Love',
        'Sexy Walk',
        'Shaped Like Itself',
        'Shared Family Quirks',
        'Shave And A Haircut',
        'She Is Not My Girlfriend',
        'Shipper on Deck',
        'Ship Tease',
        'Shoo Out the Clowns',
        'Shout-Out Theme Naming',
        'Shut Up, Hannibal! / Talk to the Fist',
        '"Shut Up" Kiss',
        'Sibling Yin-Yang',
        'Sidekick Song',
        'Skunk Stripe',
        'Slapstick Knows No Gender',
        'The Smurfette Principle',
        'Snow Means Cold',
        'Snow Means Death',
        'Softer And Slower Cover',
        'The Sociopath',
        'The title is even worse in Chinese',
        'A great Woolseyism in the Finnish translation',
        'The Stinger',
        'Storming the Castle',
        'Sugar and Ice Personality',
        'Taking the Bullet',
        'Taking You with Me',
        'Teens Are Short',
        'Terrible Trio',
        'Terrified of Germs',
        'That Man Is Dead',
        'They Died Because of You',
        'Thinking Out Loud',
        'This Cannot Be!',
        'Those Two Bad Guys',
        'Toilet Humor',
        'Tongue on the Flagpole',
        'Tragic Dream',
        'Tragic Villain',
        'Trauma Conga Line',
        'Travelling at the Speed of Plot',
        'Troubled, but Cute',
        'True Blue Femininity',
        'Unknown Rival',
        'Uptown Girl',
        'Villain Song',
        'Villain with Good Publicity',
        'Villains Never Lie',
        'Visual Pun',
        'Wacky Wayside Tribe',
        'Walk on Water',
        'Walking Spoiler',
        'Weather Dissonance',
        'We Could Have Avoided All This',
        'Wham Line',
        'What Happened to the Mouse?',
        'When She Smiles',
        'Winter Royal Lady',
        'Wrong Guy First',
        'You ALL Share My Story',
        'You Are in Command Now',
        'You Are Not Alone',
        'You Monster!',
        'Younger and Hipper'
    }))

    with flask_app.app_context():
        engine = get_database_engine()
        Base.metadata.drop_all(bind=engine)
        Base.metadata.create_all(bind=engine)
        with session.begin():
            session.add_all(works)


#: (:class:`collections.abc.Callable`) The CLI entry point.
main = cli
