language: python
python:
- 3.3
- 3.4
install:
- pip install -e .[tests]
- pip install pytest-cov flake8 coveralls
script:
- py.test -v --cov cliche --durations=20
- hooks/pre-commit
after_success:
- coveralls
notifications:
  irc:
    channels:
    - "irc.ozinger.org#cliche.io"
    on_success: change
    on_failure: always
