language: python
env:
  global:
  # Twitter
  - secure: YHLzza7Qzm+pjNCELMujjI6udoV1mI5xOJ/g0gfpftegxDFX3QAYiRyjYFp93FUQulPGw44gCxkm9zzNckXv4u+xx2c8eFRTAMwcf9WGLasjNVm6jGxUHoX4oHb7qatFTzOoH1HEvbpDibpa1qdLRMlw7m67XxJveVC2CxJetXA=
  - secure: R5TebdH6UpAgezFyVCbJbM7JhxODueFdniS1wHr5rmbGI8ONYUIPIf48BGlztrmJtA8szfilBViAE87yW41sy7gy9IIEq/M3yQanfDknwSlQxZh5fnqhf+5l7jLQxmna6SUTrYEWU5wyzESo3/OvAmF1uPRI5MsJmVeoLeyrS6w=
python:
- 3.3
- 3.4
addons:
  postgresql: "9.3"
before_install:
# gcc >= 4.7 is needed for -std=c++11
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
install:
# gcc >= 4.7 is needed for -std=c++11
- sudo apt-get install -qq gcc-4.8 g++-4.8 libstdc++-4.8-dev
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
# install cliche
- pip install -e .[tests]
- pip install pytest-cov flake8 coveralls
before_script:
- createdb -U postgres cliche_test
- createdb -U postgres alembic_test
script:
# alembic test
- echo "DATABASE_URL = 'postgresql:///alembic_test?user=postgres'" > alembic_test.cfg.py
- cliche upgrade -c alembic_test.cfg.py 27e81ea4d86
- cliche upgrade -c alembic_test.cfg.py
- cliche upgrade -c alembic_test.cfg.py 27e81ea4d86
# setup.py test
- python setup.py history -c alembic_test.cfg.py
# unit test
- py.test -v --cov cliche --durations=20 --database-url='postgresql:///cliche_test?user=postgres'
- py.test -v --durations=20
# lint
- hooks/pre-commit
after_success:
- coveralls
notifications:
  irc:
    channels:
    - "irc.ozinger.org#cliche.io"
    on_success: change
    on_failure: always
