language: python
env:
  global:
  # Note: The encrypted key under are encrypted for clicheio/cliche repository.
  # For testing, encrypt environmental variables for your own repository, and
  # re-encrypt them for clicheio/cliche repository on pull request.
  # Sentry
  - secure: "bfyH1TMzsg/ueHoWXob3YlntuEwYip4qKBlZNXlUYeXdNAt3GtHuFvsLNP82y88p66pgqW+DsWzMSuCYVlqoCAM+rTfuszzD8TB7i6DqultbiXuq+7fBjfU1xqwPUlWiC245InFFWoVTKqo8jcBUNvg7JW8td/tSgTZZAW2GhTE="
  # Twitter
  - secure: "EfV35XpgCBgwuBUhbRKdi+YgRhZezJcvtpt1ZhkB4/+CC3QBLr6gDt9Vimqvdx2ZyUa8UQP5oWQ4q0YsRQf6c3qsmFHUU6ZVzMTHvRxSZ08o87kignYnlyd+RmfpSY08exwYdSrVnLbMn8igsLHuTVV1e5yOb2P8i+sXQOQQ4X8="
  - secure: "Q2c5a4gFu9wVjOJP9V8amJr0q4JfobXHVDaEFwNj7U+qn9CfFDoAcWKPuy7NYF5nY/ShrhJ7TQfmry9yDYpantvFpt0Dpv3/INb+7t+xdy2hlIBVbcMwvqaR2DGp6Z0wsEaUop015fQnh9cvkNhKctFJsdUql3W6joNkNSfaZ0c="
python:
- 3.4
- 3.3
addons:
  postgresql: "9.3"
before_install:
# gcc >= 4.7 is needed for -std=c++11
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
install:
# gcc >= 4.7 is needed for -std=c++11
- sudo apt-get install -qq gcc-4.8 g++-4.8 libstdc++-4.8-dev
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
# install cliche
- pip install -e .[tests]
- pip install pytest-cov flake8 coveralls
before_script:
- createdb -U postgres cliche_test
- createdb -U postgres alembic_test
script:
# alembic test
- echo "DATABASE_URL = 'postgresql:///alembic_test?user=postgres'" > alembic_test.cfg.py
- cliche upgrade -c alembic_test.cfg.py 27e81ea4d86
- cliche upgrade -c alembic_test.cfg.py
- cliche upgrade -c alembic_test.cfg.py 27e81ea4d86
# setup.py test
- python setup.py history -c alembic_test.cfg.py
# unit test
- py.test -v --cov cliche --durations=20 --database-url='postgresql:///cliche_test?user=postgres'
- py.test -v --durations=20
# lint
- hooks/pre-commit
after_success:
- coveralls
notifications:
  irc:
    channels:
    - "irc.ozinger.org#cliche.io"
    on_success: change
    on_failure: always
