language: python
python:
- 3.3
- 3.4
addons:
  postgresql: "9.3"
install:
- pip install -e .[tests]
- pip install pytest-cov flake8 coveralls
before_script:
- createdb -U postgres cliche_test
script:
- py.test -v --cov cliche --durations=20 --database-url='postgresql:///cliche_test?user=postgres'
- py.test -v --durations=20
- hooks/pre-commit
after_success:
- coveralls
notifications:
  irc:
    channels:
    - "irc.ozinger.org#cliche.io"
    on_success: change
    on_failure: always
