"""Add Work and change existing one's definition by using lambda

Revision ID: 3eba2f26837
Revises: 223f67eabc3
Create Date: 2014-10-01 01:42:51.057556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eba2f26837'
down_revision = '223f67eabc3'


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
